# Generated by Django 6.0.5 on 2026-05-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_can_access_pdv_profile_can_adjust_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allow_passwordless_login',
            field=models.BooleanField(default=False, help_text='Permite login sem senha. Use apenas para usuários genéricos em ambiente controlado.'),
        ),
    ]
