# Generated by Django 6.0.5 on 2026-06-06 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_allow_passwordless_login'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='allow_passwordless_login',
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Garçom, Caixa, Gerente, Estoque, Freela sábado.', max_length=80)),
                ('can_access_pdv', models.BooleanField(default=False)),
                ('can_create_order', models.BooleanField(default=False)),
                ('can_approve_order', models.BooleanField(default=False)),
                ('can_mark_delivered', models.BooleanField(default=False)),
                ('can_cancel_pre_sale', models.BooleanField(default=False)),
                ('can_cancel_paid_order', models.BooleanField(default=False)),
                ('can_discard_paid_order', models.BooleanField(default=False)),
                ('can_view_orders_panel', models.BooleanField(default=False)),
                ('can_view_stock', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('can_create_stock_entry', models.BooleanField(default=False)),
                ('can_adjust_stock', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
            options={
                'verbose_name': 'Função',
                'verbose_name_plural': 'Funções',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='role_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='accounts.staffrole', verbose_name='Função personalizada'),
        ),
    ]
