# Generated by Django 6.0.5 on 2026-05-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='financial_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='operational_status',
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pre_sale', 'Pré-venda'), ('sold', 'Vendido'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado')], default='pre_sale', max_length=30),
        ),
    ]
