# Generated by Django 6.0.5 on 2026-05-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_financial_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pre_sale', 'Pré-venda'), ('sold', 'Vendido'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado'), ('discarded', 'Descartado')], default='pre_sale', max_length=30),
        ),
    ]
