# Generated by Django 6.0.5 on 2026-05-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('active', 'Ativa'), ('cancelled', 'Cancelada'), ('discarded', 'Descartada')], default='active', max_length=20),
        ),
    ]
