# Generated by Django 6.0.5 on 2026-05-25 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, max_length=80, null=True)),
                ('product_type', models.CharField(choices=[('sale', 'Produto de venda'), ('internal_use', 'Uso interno'), ('both', 'Venda e uso interno')], default='sale', max_length=30)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, help_text='Preço cobrado por unidade vendida. Exemplo: R$ 28 por porção.', max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('minimum_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Quantidade mínima para alerta de estoque baixo.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_mode', models.CharField(choices=[('simple', 'Entrada simples'), ('detailed', 'Entrada detalhada')], default='simple', max_length=20)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, help_text='Valor total investido. Exemplo: R$ 150 em batata.', max_digits=10)),
                ('quantity_added', models.DecimalField(decimal_places=2, help_text='Quantidade gerada. Exemplo: 30 porções ou 24 unidades.', max_digits=10)),
                ('remaining_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('package_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Opcional. Exemplo: 6 caixas, 3 sacos.', max_digits=10, null=True)),
                ('package_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Opcional. Exemplo: R$ 25 por saco.', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='products.product')),
            ],
            options={
                'verbose_name': 'Entrada de estoque',
                'verbose_name_plural': 'Entradas de estoque',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('sale', 'Venda'), ('loss', 'Perda'), ('internal_use', 'Uso interno'), ('courtesy', 'Cortesia'), ('adjustment_positive', 'Ajuste positivo'), ('adjustment_negative', 'Ajuste negativo'), ('stock_count', 'Conferência')], max_length=30)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reason', models.CharField(blank=True, max_length=120, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('stock_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='products.stockentry')),
            ],
            options={
                'verbose_name': 'Movimento de estoque',
                'verbose_name_plural': 'Movimentos de estoque',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'ordering': ['name'],
                'unique_together': {('company', 'symbol')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.unit'),
        ),
    ]
