# Generated by Django 6.0.5 on 2026-05-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('sale', 'Venda'), ('loss', 'Perda'), ('internal_use', 'Uso interno'), ('courtesy', 'Cortesia'), ('adjustment_positive', 'Ajuste positivo'), ('adjustment_negative', 'Ajuste negativo'), ('return_to_stock', 'Retorno ao estoque'), ('stock_count', 'Conferência')], max_length=30),
        ),
    ]
